### ISSUE TITLE
Create chat server

### ISSUE THREAD

**Issue by stormy131** [metarhia/Metanet#1]
Create chat server using sockets (socket.io)

**Comment by tshemsedinov** [comment]
Socket.io is a piece of legacy crappy code, not actual for 2021. We have native websockets at frontend everywhere; we have small and reliable dependency `ws` at backend but already working on implementation websockets without `ws` with pure nodejs. @stormy131

As of now we have a simple chat server example in Example, see following files:
1. Domain logic: https://github.com/metarhia/Example/blob/master/application/domain/chat.js
2. API: https://github.com/metarhia/Example/tree/master/application/api/chat.1

It's just a prototype but it works and can be extended / improved.
